// ── Pandit et al. 2018 ───────────────────────────────────────────────────────
// "Microbial diversity and community composition of caecal microbiota in
//  commercial and indigenous Indian chickens determined using 16s rDNA
//  amplicon sequencing"
// Microbiome, 2018. DOI: 10.1186/s40168-018-0501-9
// ─────────────────────────────────────────────────────────────────────────────
// 16S rRNA amplicon sequencing (Illumina MiSeq) of caecal microbiota from
// 30 chickens: Aseel and Kadaknath (indigenous) vs Cobb400 and Ross 308
// (commercial broilers) at two locations in India (Anand, Gujarat &
// Chennai, Tamil Nadu). All sampled at 42 days post-hatch.
// ─────────────────────────────────────────────────────────────────────────────

const BIOPROJ = "NCBI BioProject PRJEB22231; MG-RAST multiple accessions";
const BIOPROJ_FULL = "NCBI BioProject PRJEB22231; MG-RAST multiple accessions (4680540.3, 4680543.3, 4680545.3, 4680547.3, 4680548.3, 4680550.3, 4680552.3, 4680554.3, 4680555.3, 4680557.3, 4680558.3, 4680560.3, 4680562.3, 4680563.3, 4680565.3, 4681303.3–4681332.3, 4692159.3–4692371.3)";
const COMMON = {
  fermentation_type: "N/A - animal gut microbiome (chicken caecal lumen)",
  dna_extraction_kit: "QIAamp Fast DNA Stool Mini kit (QIAGEN) with modifications; DNase-free RNase (Macherey-Nagel) treatment",
  primers: "P1 (V1-V2, 65°C), P2 (V3-V4, 60°C), P3 (V5-V6, 66°C); P2 selected for detailed analysis",
  read_type: "Illumina MiSeq paired-end; avg 115,010 sequences/sample; 10.35M total",
  sequencing_facility: "Dept. of Agricultural Biotechnology (Centre of Excellence in Biotechnology), AAU, Anand, India",
  bioinformatics_pipeline: "MG-RAST V3.6, SolexaQA, STAMP v2.1.3 (Benjamini-Hochberg FDR), METAGENassist (Pareto Scaling), PAST v2.17c (PCoA/ANOSIM), QIIME (97% OTU/UniFrac/rarefaction), BoxPlotR, Venny 2.1, LEfSe (KW α=0.05, LDA>3.5)",
  database: "RDP (Ribosomal Database Project) via MG-RAST (min e-value 1E-5, min identity 80%)",
  otu_clustering: "97% sequence similarity OTU clustering (QIIME); rarefied at 10,000 sequences/sample",
  classifier: "MG-RAST with RDP database taxonomy assignment",
};

// [code, food_name, location, description_suffix]
const SAMPLE_META = [
  ["APA", "Aseel chicken caecal content (Anand)",              "Anand, Gujarat, India (Location 1: AAU Central Poultry Research Station)",  "5 chickens sampled at 42 days. Total sequences: 839,375; Avg/sample: 55,958; Avg OTUs: 1,134; Good's coverage: 94.6%"],
  ["APK", "Kadaknath chicken caecal content (Anand)",          "Anand, Gujarat, India (Location 1: AAU Central Poultry Research Station)",  "5 chickens sampled at 42 days. Total sequences: 1,042,538; Avg/sample: 69,503; Avg OTUs: 816; Good's coverage: 95.9%. Lowest OTU count among all groups"],
  ["APC", "Cobb400 commercial broiler caecal content (Anand)", "Anand, Gujarat, India (Location 1: AAU Central Poultry Research Station)",  "5 chickens sampled at 42 days. Total sequences: 679,158; Avg/sample: 45,277; Avg OTUs: 1,273; Good's coverage: 94.1%. Highest OTU count at Location 1"],
  ["TPA", "Aseel chicken caecal content (Tamil Nadu)",              "Chennai, Tamil Nadu, India (Location 2: TANUVAS)",  "5 chickens sampled at 42 days. Total sequences: 2,775,511; Avg/sample: 185,034; Avg OTUs: 735; Good's coverage: 95.7%"],
  ["TPK", "Kadaknath chicken caecal content (Tamil Nadu)",          "Chennai, Tamil Nadu, India (Location 2: TANUVAS)",  "5 chickens sampled at 42 days. Total sequences: 2,548,471; Avg/sample: 164,390; Avg OTUs: 833; Good's coverage: 95.6%. Notable for high Fusobacteria (41.3% at phylum level)"],
  ["TPC", "Ross 308 commercial broiler caecal content (Tamil Nadu)","Chennai, Tamil Nadu, India (Location 2: TANUVAS)",  "5 chickens sampled at 42 days. Total sequences: 2,465,845; Avg/sample: 169,898; Avg OTUs: 645; Good's coverage: 97.0% (highest coverage)"],
];

// Pooled composition: [taxon_name, rank, relative_abundance, is_dominant, notes]
const COMP_ALL = [
  // Phyla
  ["Bacteroidetes",  "phylum", 40.0,  true,  "Dominant phylum; with Firmicutes accounts for >80% of sequences in most samples"],
  ["Firmicutes",     "phylum", 40.0,  true,  "Dominant phylum; contributes to butyrate and propionate synthesis"],
  ["Actinobacteria", "phylum",  8.5,  false, "Represented with unclassified bacteria at 8.5-18.3% across all breeds"],
  ["Fusobacteria",   "phylum",  5.0,  false, "More common at Location 2 (Tamil Nadu); 41.3% in Kadaknath at Location 2"],
  ["Proteobacteria", "phylum",  3.0,  false, "Present across all breeds; includes potential pathogenic genera"],
  // Classes
  ["Bacteroidia",    "class",  35.0,  true,  "Predominant class in most breeds; p<8.9E-06"],
  ["Clostridia",     "class",  35.0,  true,  "Abundant in all chickens; more common at Location 1 (Anand); p<4.1E-07"],
  ["Fusobacteriia",  "class",   5.0,  false, "Common in chickens at Location 2 (Tamil Nadu); p<1.4E-07"],
  // Genera — dominant/core
  ["Bacteroides",    "genus",  20.0,  true,  "Most common genus in all breeds except Cobb400 at Location 1; polysaccharide degradation and SCFA formation; p<7.2E-05"],
  ["Clostridium",    "genus",  10.0,  true,  "Higher proportion in Cobb400 at Location 1; p<2.1E-03"],
  ["Alistipes",      "genus",   8.0,  false, "Common in Kadaknath at Location 1; p<1.0E-07"],
  ["Faecalibacterium","genus",  5.0,  false, "Dominant genus (Abstract); butyrate production"],
  ["Fusobacterium",  "genus",   4.0,  false, "Potential pathogen; biomarker for Kadaknath at Location 2; negatively correlated with beneficial genera"],
  ["Blautia",        "genus",   4.0,  false, "Butyrate production; core genus; positive contribution to host"],
  ["Eubacterium",    "genus",   3.0,  false, "Dominant genus (Abstract); SCFA metabolism"],
  ["Ruminococcus",   "genus",   3.0,  false, "Core caecal genus; starch hydrolysis and SCFA formation"],
  ["Prevotella",     "genus",   3.0,  false, "Core caecal genus; propionate production; negative correlations with pathogens in Aseel"],
  ["Megamonas",      "genus",   2.0,  false, "Biomarker for Cobb400"],
  ["Butyrivibrio",   "genus",   2.0,  false, "Butyrate production; positively correlated with other metabolic genera"],
  ["Lactobacillus",  "genus",   2.0,  false, "Probiotic effects; biomarker for Cobb400; positively correlated with Bacillus in Cobb400"],
  ["Bacillus",       "genus",   2.0,  false, "Core caecal genus; positively correlated with Lactobacillus in Cobb400"],
  ["Selenomonas",    "genus",   2.0,  false, "Biomarker for Ross 308"],
  ["Acidaminococcus","genus",   2.0,  false, "Biomarker for Ross 308"],
  ["Barnesiella",    "genus",   2.0,  false, "Biomarker for Ross 308; core caecal genus"],
  ["Butyricimonas",  "genus",   2.0,  false, "Biomarker for Ross 308; core caecal genus"],
  ["Campylobacter",  "genus",   1.5,  false, "Potential pathogen; detected >1.0% in Kadaknath (Location 2) and Aseel (both); biomarker for Kadaknath at Location 2; absent in commercial lines"],
  ["Enterococcus",   "genus",   1.5,  false, "Potential pathogen; biomarker for Kadaknath at Location 2; positively correlated with other pathogens in Aseel"],
  ["Porphyromonas",  "genus",   1.5,  false, "Biomarker for Aseel; propionate production"],
  ["Paraprevotella", "genus",   1.5,  false, "Core caecal genus; biomarker for Aseel"],
  ["Megasphaera",    "genus",   1.5,  false, "Biomarker for Aseel"],
  ["Helicobacter",   "genus",   1.0,  false, "Potential pathogen/zoonotic; biomarker for Aseel at Location 2"],
  ["Cronobacter",    "genus",   1.0,  false, "Potential pathogen; biomarker for Kadaknath at Location 2"],
  ["Cellulosilyticum","genus",  1.0,  false, "Core caecal genus; cellulose degradation and SCFA formation"],
  ["Deferribacter",  "genus",   1.0,  false, "Biomarker for Aseel"],
  ["Abiotrophia",    "genus",   1.0,  false, "Biomarker for Aseel"],
  ["Desulfovibrio",  "genus",   1.0,  false, "Biomarker for Kadaknath; sulfate-reducing bacteria"],
  ["Ornithobacterium","genus",  1.0,  false, "Biomarker for Kadaknath"],
  ["Symbiobacterium","genus",   1.0,  false, "Biomarker for Kadaknath"],
  ["Desulfohalobium","genus",   1.0,  false, "Biomarker for Cobb400; negatively correlated with most other genera"],
  ["Desulfotomaculum","genus",  1.0,  false, "Biomarker for Cobb400"],
  ["Roseburia",      "genus",   1.0,  false, "Biomarker for Cobb400; butyrate production"],
  ["Actinomyces",    "genus",   1.0,  false, "Biomarker for Cobb400"],
  ["Ethanoligenens", "genus",   1.0,  false, "Biomarker for Cobb400"],
  ["Pectinatus",     "genus",   1.0,  false, "Biomarker for Cobb400"],
  ["Parabacteroides","genus",   1.0,  false, "Core caecal genus"],
  ["Rikenella",      "genus",   1.0,  false, "Core caecal genus"],
  ["Pseudobutyrivibrio","genus",1.0,  false, "Core caecal genus; butyrate production"],
  ["Butyricicoccus", "genus",   1.0,  false, "Core caecal genus"],
  ["Desulfonauticus","genus",   1.0,  false, "Sulfate-reducing bacteria"],
  ["Phascolarctobacterium","genus",1.0,false,"Short-chain fatty acid producer"],
  ["Anaerotruncus",  "genus",   1.0,  false, "Core caecal genus"],
  ["Subdoligranulum","genus",   1.0,  false, "Core caecal genus"],
];

const ALL_CODE = "ALL";
const ALL_FOOD = "Chicken caecal microbiota (pooled)";
const ALL_DESC = "Pooled across all 30 chickens (5 per breed per location), all breeds and locations";

const bacterial_composition = COMP_ALL.map(([taxon_name, reported_rank, relative_abundance, is_dominant, notes]) => ({
  sample_code: ALL_CODE, food_name: ALL_FOOD, description: ALL_DESC,
  taxon_name, reported_rank, relative_abundance, is_dominant,
  measurement_type: "relative_abundance", notes,
}));

// Genera list (for taxonomy_list)
const GENERA = [
  "Bacteroides","Alistipes","Faecalibacterium","Clostridium","Blautia","Eubacterium",
  "Ruminococcus","Butyrivibrio","Lactobacillus","Bacillus","Campylobacter","Fusobacterium",
  "Helicobacter","Prevotella","Megamonas","Butyricicoccus","Paraprevotella","Parabacteroides",
  "Porphyromonas","Barnesiella","Butyricimonas","Rikenella","Cellulosilyticum","Pseudobutyrivibrio",
  "Roseburia","Acidaminococcus","Selenomonas","Desulfovibrio","Desulfohalobium","Desulfonauticus",
  "Desulfotomaculum","Symbiobacterium","Cronobacter","Enterococcus","Veillonella","Anaerotruncus",
  "Subdoligranulum","Oscillibacter","Anaerostipes","Coprococcus","Dorea","Streptococcus",
  "Eggerthella","Geobacillus","Slackia","Phascolarctobacterium","Deferribacter","Atopobium",
  "Tannerella","Acetobacterium","Ethanoligenens","Pectinatus","Alkaliphilus","Actinomyces",
  "Anaeroplasma","Mycoplasma","Turicibacter","Holdemania","Sporobacter","Pseudoflavonifractor",
  "Flavonifractor","Intestinimonas","Sutterella","Parasutterella","Odoribacter","Paludibacter",
  "Proteiniphilum","Megasphaera","Ornithobacterium","Abiotrophia","Cyclobacterium",
  "Caldicellulosiruptor","Thermobaculum","Caulobacter","Cytophaga","Oceanimonas","Tepidimicrobium",
  "Candidatus Phytoplasma","Zunongwangia","Marinifilum","Ureaplasma","Drancunculibacter","Phocea",
  "unclassified bacteria","unclassified Clostridiales","unclassified Gammaproteobacteria",
  "unclassified Lachnospiraceae","unclassified Ruminococcaceae","unclassified Erysipelotrichaceae",
  "unclassified Deltaproteobacteria","unclassified Alphaproteobacteria","unclassified Bacteria",
];

export default {
  source_paper: {
    title: "Microbial diversity and community composition of caecal microbiota in commercial and indigenous Indian chickens determined using 16s rDNA amplicon sequencing",
    authors: "Ramesh J. Pandit, Ankit T. Hinsu, Namrata V. Patel, Prakash G. Koringa, Subhash J. Jakhesara, Jalpa R. Thakkar, Tejas M. Shah, Georgina Limon, Androniki Psifidi, Javier Guitian, David A. Hume, Fiona M. Tomley, Dharamshibhai N. Rank, M. Raman, K.G. Tirumurugaan, Damer P. Blake, Chaitanya G. Joshi",
    journal: "Microbiome",
    year: 2018,
    doi: "10.1186/s40168-018-0501-9",
    link: "https://doi.org/10.1186/s40168-018-0501-9",
  },
  sequencing_methods: [
    { method_name: "16S rRNA amplicon sequencing", platform: "Illumina MiSeq", target_region: "V1-V2 (P1), V3-V4 (P2), V5-V6 (P3)" },
  ],
  samples: [
    ...SAMPLE_META.map(([sample_code, food_name, location, desc_suffix]) => ({
      sample_code, food_name,
      description: `Caecal contents from indigenous/commercial chickens raised at ${location}. ${desc_suffix}.`,
      raw_material: "Chicken caecal contents (both caecal pouches, pooled per individual)",
      location,
      collection_day: "42 days post-hatch",
      replicates: "5 individual chickens",
      accession_id: BIOPROJ,
      additional_info: COMMON,
    })),
    {
      sample_code: ALL_CODE,
      food_name: ALL_FOOD,
      description: "Pooled dataset combining all 30 chicken caecal samples from both locations and all breeds/lines (Aseel, Kadaknath, Cobb400, Ross 308). P2 (V3-V4) selected for detailed analysis. 10.35M total sequences, 19.41 Gbp, avg Good's coverage 95.48%.",
      raw_material: "Chicken caecal contents (both caecal pouches, pooled per individual)",
      location: "Anand, Gujarat and Chennai, Tamil Nadu, India",
      collection_day: "42 days post-hatch",
      replicates: "30 individual chickens (5 per breed per location)",
      accession_id: BIOPROJ_FULL,
      additional_info: COMMON,
    },
  ],
  taxonomy_list: [
    // Phyla
    { name: "Bacteroidetes",   rank: "phylum", reported_rank: "Phylum" },
    { name: "Firmicutes",      rank: "phylum", reported_rank: "Phylum" },
    { name: "Actinobacteria",  rank: "phylum", reported_rank: "Phylum" },
    { name: "Fusobacteria",    rank: "phylum", reported_rank: "Phylum" },
    { name: "Proteobacteria",  rank: "phylum", reported_rank: "Phylum" },
    { name: "Spirochaetes",    rank: "phylum", reported_rank: "Phylum" },
    { name: "Synergistetes",   rank: "phylum", reported_rank: "Phylum" },
    { name: "Flavobacteria",   rank: "phylum", reported_rank: "Phylum" },
    // Classes
    { name: "Bacteroidia",           rank: "class", reported_rank: "Class" },
    { name: "Clostridia",            rank: "class", reported_rank: "Class" },
    { name: "Fusobacteriia",         rank: "class", reported_rank: "Class" },
    { name: "Bacilli",               rank: "class", reported_rank: "Class" },
    { name: "Negativicutes",         rank: "class", reported_rank: "Class" },
    { name: "Epsilonproteobacteria", rank: "class", reported_rank: "Class" },
    { name: "Deltaproteobacteria",   rank: "class", reported_rank: "Class" },
    { name: "Gammaproteobacteria",   rank: "class", reported_rank: "Class" },
    { name: "Spirochaetia",          rank: "class", reported_rank: "Class" },
    { name: "Synergistia",           rank: "class", reported_rank: "Class" },
    { name: "Flavobacteriia",        rank: "class", reported_rank: "Class" },
    // Orders
    { name: "Bacteroidales",      rank: "order", reported_rank: "Order" },
    { name: "Clostridiales",      rank: "order", reported_rank: "Order" },
    { name: "Fusobacteriales",    rank: "order", reported_rank: "Order" },
    { name: "Lactobacillales",    rank: "order", reported_rank: "Order" },
    { name: "Bacillales",         rank: "order", reported_rank: "Order" },
    { name: "Campylobacterales",  rank: "order", reported_rank: "Order" },
    { name: "Desulfovibrionales", rank: "order", reported_rank: "Order" },
    { name: "Spirochaetales",     rank: "order", reported_rank: "Order" },
    { name: "Synergistales",      rank: "order", reported_rank: "Order" },
    { name: "Flavobacteriales",   rank: "order", reported_rank: "Order" },
    { name: "Enterobacteriales",  rank: "order", reported_rank: "Order" },
    // Families
    { name: "Bacteroidaceae",         rank: "family", reported_rank: "Family" },
    { name: "Porphyromonadaceae",     rank: "family", reported_rank: "Family" },
    { name: "Prevotellaceae",         rank: "family", reported_rank: "Family" },
    { name: "Rikenellaceae",          rank: "family", reported_rank: "Family" },
    { name: "Lachnospiraceae",        rank: "family", reported_rank: "Family" },
    { name: "Clostridiaceae",         rank: "family", reported_rank: "Family" },
    { name: "Ruminococcaceae",        rank: "family", reported_rank: "Family" },
    { name: "Eubacteriaceae",         rank: "family", reported_rank: "Family" },
    { name: "Lactobacillaceae",       rank: "family", reported_rank: "Family" },
    { name: "Bacillaceae",            rank: "family", reported_rank: "Family" },
    { name: "Veillonellaceae",        rank: "family", reported_rank: "Family" },
    { name: "Fusobacteriaceae",       rank: "family", reported_rank: "Family" },
    { name: "Campylobacteraceae",     rank: "family", reported_rank: "Family" },
    { name: "Helicobacteraceae",      rank: "family", reported_rank: "Family" },
    { name: "Desulfohalobiaceae",     rank: "family", reported_rank: "Family" },
    { name: "Erysipelotrichaceae",    rank: "family", reported_rank: "Family" },
    { name: "Acidaminococcaceae",     rank: "family", reported_rank: "Family" },
    { name: "Enterobacteriaceae",     rank: "family", reported_rank: "Family" },
    { name: "Enterococcaceae",        rank: "family", reported_rank: "Family" },
    { name: "Deferrisomataceae",      rank: "family", reported_rank: "Family" },
    { name: "Cytophagaceae",          rank: "family", reported_rank: "Family" },
    { name: "Cyclobacteriaceae",      rank: "family", reported_rank: "Family" },
    { name: "Caldicellulosiruptoraceae", rank: "family", reported_rank: "Family" },
    { name: "Thermobaculaceae",       rank: "family", reported_rank: "Family" },
    { name: "Caulobacteraceae",       rank: "family", reported_rank: "Family" },
    { name: "Desulfovibrionaceae",    rank: "family", reported_rank: "Family" },
    { name: "Slackiaceae",            rank: "family", reported_rank: "Family" },
    { name: "Phascolarctobacteriaceae",rank: "family", reported_rank: "Family" },
    { name: "Oceanimonadaceae",       rank: "family", reported_rank: "Family" },
    { name: "Tepidimicrobiaceae",     rank: "family", reported_rank: "Family" },
    { name: "Acholeplasmataceae",     rank: "family", reported_rank: "Family" },
    { name: "Atopobiaceae",           rank: "family", reported_rank: "Family" },
    { name: "Tannerellaceae",         rank: "family", reported_rank: "Family" },
    { name: "Flavobacteriaceae",      rank: "family", reported_rank: "Family" },
    { name: "Ethanoligenensaceae",    rank: "family", reported_rank: "Family" },
    { name: "Pectinaceae",            rank: "family", reported_rank: "Family" },
    { name: "Alkaliphilaceae",        rank: "family", reported_rank: "Family" },
    { name: "Desulfotomaculaceae",    rank: "family", reported_rank: "Family" },
    { name: "Roseburiaceae",          rank: "family", reported_rank: "Family" },
    { name: "Anaeroplasmataceae",     rank: "family", reported_rank: "Family" },
    { name: "Turicibacteraceae",      rank: "family", reported_rank: "Family" },
    { name: "Holdemaniaceae",         rank: "family", reported_rank: "Family" },
    { name: "Sporobacteraceae",       rank: "family", reported_rank: "Family" },
    { name: "Pseudoflavonifractoraceae", rank: "family", reported_rank: "Family" },
    { name: "Flavonifractoraceae",    rank: "family", reported_rank: "Family" },
    { name: "Intestinimonadaceae",    rank: "family", reported_rank: "Family" },
    { name: "Drancunculibacteraceae", rank: "family", reported_rank: "Family" },
    { name: "Phoceaceae",             rank: "family", reported_rank: "Family" },
    { name: "Sutterellaceae",         rank: "family", reported_rank: "Family" },
    { name: "Parasutterellaceae",     rank: "family", reported_rank: "Family" },
    { name: "Odoribacteraceae",       rank: "family", reported_rank: "Family" },
    { name: "Paludibacteraceae",      rank: "family", reported_rank: "Family" },
    { name: "Proteiniphilaceae",      rank: "family", reported_rank: "Family" },
    { name: "Megasphaeraceae",        rank: "family", reported_rank: "Family" },
    { name: "Butyricicoccaceae",      rank: "family", reported_rank: "Family" },
    { name: "Paraprevotellaceae",     rank: "family", reported_rank: "Family" },
    { name: "Parabacteroidaceae",     rank: "family", reported_rank: "Family" },
    { name: "Butyrivibrioaceae",      rank: "family", reported_rank: "Family" },
    { name: "Pseudobutyrivibrioaceae",rank: "family", reported_rank: "Family" },
    { name: "Anaerotruncaceae",       rank: "family", reported_rank: "Family" },
    { name: "Subdoligranulaceae",     rank: "family", reported_rank: "Family" },
    { name: "Oscillibacteraceae",     rank: "family", reported_rank: "Family" },
    { name: "Anaerostipaceae",        rank: "family", reported_rank: "Family" },
    { name: "Coprococcaceae",         rank: "family", reported_rank: "Family" },
    { name: "Doreaceae",              rank: "family", reported_rank: "Family" },
    { name: "Streptococcaceae",       rank: "family", reported_rank: "Family" },
    { name: "Ureaplasmataceae",       rank: "family", reported_rank: "Family" },
    { name: "Eggerthellaceae",        rank: "family", reported_rank: "Family" },
    { name: "Geobacillaceae",         rank: "family", reported_rank: "Family" },
    { name: "Cellulosilyticaceae",    rank: "family", reported_rank: "Family" },
    { name: "Marinifilaceae",         rank: "family", reported_rank: "Family" },
    { name: "Desulfonauticaceae",     rank: "family", reported_rank: "Family" },
    { name: "Symbiobacteraceae",      rank: "family", reported_rank: "Family" },
    { name: "Ornithobacteriaceae",    rank: "family", reported_rank: "Family" },
    { name: "Selenomonadaceae",       rank: "family", reported_rank: "Family" },
    { name: "Megamonadaceae",         rank: "family", reported_rank: "Family" },
    { name: "Butyricimonadaceae",     rank: "family", reported_rank: "Family" },
    { name: "Barnesiellaceae",        rank: "family", reported_rank: "Family" },
    // Genera
    ...GENERA.map(name => ({ name, rank: "genus", reported_rank: "Genus" })),
  ],
  bacterial_composition,
};
