export default {
  "source_paper": {
    "title": "16s rRNA Amplicon Sequencing Approach for Community and Predictive Functional Diversity of Therapeutically Valuable Formulation of Cow-derivatives",
    "authors": "Nilam Vaghamshi, Himani Gandhi, Urvisha Beladiya, Amitsingh Mangrola, Pravin Dudhagara, Rajesh Patel, Rajesh Chaudhari",
    "journal": "Bioscience Biotechnology Research Communications",
    "year": 2022,
    "doi": null,
    "link": "https://bbrc.in/"
  },
  "sequencing_methods": [
    {
      "method_name": "16S rRNA amplicon sequencing",
      "platform": "Illumina MiSeq",
      "target_region": "V3-V4"
    }
  ],
  "samples": [
    {
      "sample_code": "PG-3H",
      "food_name": "Panchagavya (3-hour old)",
      "description": "Fresh Panchagavya prepared by mixing equal proportions of fresh cow dung, urine, milk, curd, and ghee, allowed to stand for three hours, then filtered through muslin cloth",
      "raw_material": "Cow dung, cow urine, milk, curd (yogurt), ghee (clarified butter)",
      "location": "Madhuvan Dairy Farm, Haldarva, Bharuch, Gujarat, India",
      "collection_day": "3 hours after mixing (fresh preparation)",
      "replicates": "Single sample",
      "accession_id": "EBI-Metagenomics (accession number not explicitly stated in text)",
      "additional_info": {
        "fermentation_type": "spontaneous",
        "dna_extraction_kit": "HiPurA Stool DNA Purification Kit (MB544)",
        "primers": "V3-V4 region primers (specific sequences not provided)",
        "read_type": "2D FASTQ (paired-end)",
        "sequencing_facility": "Not explicitly stated",
        "bioinformatics_pipeline": "FASTQC, Pear, One Codex, Kraken, MG-RAST, SILVAngs, MicrobiomeAnalyst, Tax4Fun, KO and KEGG mapper",
        "database": "One Codex (k-mer based), MG-RAST, Kraken, SILVA, KEGG",
        "otu_clustering": "k-mer based classification (One Codex), sequence clustering",
        "classifier": "One Codex, Kraken, MG-RAST"
      }
    }
  ],
  "taxonomy_list": [
    {"name": "Bacteria", "rank": "domain", "reported_rank": "Domain"},
    {"name": "Firmicutes", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Bacteroidetes", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Proteobacteria", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Actinobacteria", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Verrucomicrobia", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Planctomycetes", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Spirochaetes", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Aquificae", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Synergistetes", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Acidobacteria", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Thermotogae", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Deferribacteres", "rank": "phylum", "reported_rank": "Phylum"},
    {"name": "Clostridiales", "rank": "order", "reported_rank": "Order"},
    {"name": "Bacteroidales", "rank": "order", "reported_rank": "Order"},
    {"name": "Ruminococcaceae", "rank": "family", "reported_rank": "Family"},
    {"name": "Lachnospiraceae", "rank": "family", "reported_rank": "Family"},
    {"name": "Bacteroidaceae", "rank": "family", "reported_rank": "Family"},
    {"name": "Enterobacteriaceae", "rank": "family", "reported_rank": "Family"},
    {"name": "Moraxellaceae", "rank": "family", "reported_rank": "Family"},
    {"name": "Streptomyces", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Lactococcus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Lactobacillus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Bacillus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Paenibacillus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Pseudomonas", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Azotobacter", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Azospirillum", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Rhizobium", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Acetobacter", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Micrococcus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Leuconostoc", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Enterococcus", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Microbacterium", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Pseudoxanthomonas", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Corynebacterium", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Escherichia", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Shigella", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Rhodobacter", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Saccharomyces", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Rhodopseudomonas", "rank": "genus", "reported_rank": "Genus"},
    {"name": "Streptomyces griseocarneus", "rank": "species", "reported_rank": "Species"},
    {"name": "Clostridiales bacterium", "rank": "species", "reported_rank": "Species"},
    {"name": "Bacteroidales bacterium", "rank": "species", "reported_rank": "Species"},
    {"name": "Verrucomicrobia bacterium", "rank": "species", "reported_rank": "Species"},
    {"name": "Lactococcus termiticola", "rank": "species", "reported_rank": "Species"},
    {"name": "Lactococcus fujiensis JCM 16395", "rank": "species", "reported_rank": "Species"},
    {"name": "Lactococcus fujiensis", "rank": "species", "reported_rank": "Species"},
    {"name": "Bacillus cereus", "rank": "species", "reported_rank": "Species"},
    {"name": "Bacillus subtilis", "rank": "species", "reported_rank": "Species"},
    {"name": "Lactobacillus camellia", "rank": "species", "reported_rank": "Species"},
    {"name": "Lactobacillus ozone", "rank": "species", "reported_rank": "Species"},
    {"name": "Leptotrichiaceae bacterium", "rank": "species", "reported_rank": "Species"},
    {"name": "Thermotogales bacterium Thermo_G1", "rank": "species", "reported_rank": "Species"},
    {"name": "Desulfitisporillum indicum S5", "rank": "species", "reported_rank": "Species"},
    {"name": "unclassified Bacteria", "rank": "species", "reported_rank": "Species"},
    {"name": "unclassified Lactobacillaceae", "rank": "species", "reported_rank": "Species"},
    {"name": "unclassified Clostridiaceae", "rank": "species", "reported_rank": "Species"}
  ],
  "bacterial_composition": [
    // Phylum level - ALL pooled
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Firmicutes", "reported_rank": "phylum", "relative_abundance": 50.08, "is_dominant": true, "measurement_type": "relative_abundance", "notes": "Most abundant phylum in Panchagavya metagenome"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Bacteroidetes", "reported_rank": "phylum", "relative_abundance": 20.79, "is_dominant": true, "measurement_type": "relative_abundance", "notes": "Second most abundant phylum"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Proteobacteria", "reported_rank": "phylum", "relative_abundance": 9.63, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Third most abundant phylum"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Actinobacteria", "reported_rank": "phylum", "relative_abundance": 3.47, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Verrucomicrobia", "reported_rank": "phylum", "relative_abundance": 1.97, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Planctomycetes", "reported_rank": "phylum", "relative_abundance": 1.21, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Spirochaetes", "reported_rank": "phylum", "relative_abundance": 0.99, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "unclassified Bacteria", "reported_rank": "phylum", "relative_abundance": 0.81, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Unclassified bacteria present"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Aquificae", "reported_rank": "phylum", "relative_abundance": 0.10, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Synergistetes", "reported_rank": "phylum", "relative_abundance": 0.09, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Acidobacteria", "reported_rank": "phylum", "relative_abundance": 0.04, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Leptotrichiaceae bacterium", "reported_rank": "phylum", "relative_abundance": 0.04, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Thermotogales bacterium Thermo_G1", "reported_rank": "phylum", "relative_abundance": 0.005, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Deferribacteres", "reported_rank": "phylum", "relative_abundance": 0.005, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Desulfitisporillum indicum S5", "reported_rank": "phylum", "relative_abundance": 0.005, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},

    // Family level - ALL pooled
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Ruminococcaceae", "reported_rank": "family", "relative_abundance": 8.46, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Most abundant family"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Lachnospiraceae", "reported_rank": "family", "relative_abundance": 7.34, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Second most abundant family"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Bacteroidaceae", "reported_rank": "family", "relative_abundance": 3.57, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Enterobacteriaceae", "reported_rank": "family", "relative_abundance": 3.27, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Moraxellaceae", "reported_rank": "family", "relative_abundance": 3.12, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "unclassified Lactobacillaceae", "reported_rank": "family", "relative_abundance": 2.0, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "unclassified Clostridiaceae", "reported_rank": "family", "relative_abundance": 1.0, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},

    // Species level - ALL pooled
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Streptomyces griseocarneus", "reported_rank": "species", "relative_abundance": 2.65, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Most abundant species; antibiotic-producing species associated with streptomycin biosynthesis"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Clostridiales bacterium", "reported_rank": "species", "relative_abundance": 2.26, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Second most abundant species; anaerobic bacterium"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Bacteroidales bacterium", "reported_rank": "species", "relative_abundance": 1.38, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Third most abundant species"},
    {"sample_code": "ALL", "food_name": "Panchagavya (pooled)", "description": "Overall combined dataset composition from 16S rRNA amplicon sequencing", "taxon_name": "Verrucomicrobia bacterium", "reported_rank": "species", "relative_abundance": 1.13, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Fourth most abundant species"},

    // Individual sample PG-3H - Phylum
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Firmicutes", "reported_rank": "phylum", "relative_abundance": 50.08, "is_dominant": true, "measurement_type": "relative_abundance", "notes": "Most abundant phylum; includes Lactococcus, Lactobacillus, Bacillus, Clostridiales"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Bacteroidetes", "reported_rank": "phylum", "relative_abundance": 20.79, "is_dominant": true, "measurement_type": "relative_abundance", "notes": "Second most abundant phylum"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Proteobacteria", "reported_rank": "phylum", "relative_abundance": 9.63, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Includes Pseudomonas, Azotobacter, Rhizobium, Acetobacter, Rhodobacter"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Actinobacteria", "reported_rank": "phylum", "relative_abundance": 3.47, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Includes Streptomyces (antibiotic-producing)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Verrucomicrobia", "reported_rank": "phylum", "relative_abundance": 1.97, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Planctomycetes", "reported_rank": "phylum", "relative_abundance": 1.21, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},

    // Individual sample PG-3H - Family
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Ruminococcaceae", "reported_rank": "family", "relative_abundance": 8.46, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Most abundant family"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Lachnospiraceae", "reported_rank": "family", "relative_abundance": 7.34, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Second most abundant family"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Bacteroidaceae", "reported_rank": "family", "relative_abundance": 3.57, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Enterobacteriaceae", "reported_rank": "family", "relative_abundance": 3.27, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Moraxellaceae", "reported_rank": "family", "relative_abundance": 3.12, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Present in Panchagavya"},

    // Individual sample PG-3H - Species
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Streptomyces griseocarneus", "reported_rank": "species", "relative_abundance": 2.65, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Most abundant species; associated with streptomycin biosynthesis pathway; antibiotic-producing species contributing to antimicrobial properties"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Clostridiales bacterium", "reported_rank": "species", "relative_abundance": 2.26, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Second most abundant species; anaerobic bacterium"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Bacteroidales bacterium", "reported_rank": "species", "relative_abundance": 1.38, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Third most abundant species"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Fresh Panchagavya prepared at Madhuvan Dairy Farm, Haldarva, Bharuch, India; mixed equal proportions of cow dung, urine, milk, curd, and ghee, allowed to stand for 3 hours", "taxon_name": "Verrucomicrobia bacterium", "reported_rank": "species", "relative_abundance": 1.13, "is_dominant": false, "measurement_type": "relative_abundance", "notes": "Fourth most abundant species"},

    // Culture-dependent presence-only taxa
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Lactobacillus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Leo et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Saccharomyces", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Leo et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Streptomyces", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Leo et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Rhodopseudomonas", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Leo et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Azospirillum", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Dhama et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Azotobacter", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Dhama et al., 2013; Ram et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Pseudomonas", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Ram et al., 2013)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Acetobacter", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Bacillus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Micrococcus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Leuconostoc", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Enterococcus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Microbacterium", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Pseudoxanthomonas", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Corynebacterium", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Escherichia", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Paenibacillus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Shigella", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Rhodobacter", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015)"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Bacteria previously isolated from Panchagavya by culture-dependent methods as cited in literature", "taxon_name": "Lactococcus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Previously isolated by culture-dependent methods (Anandham et al., 2015); also detected in metagenome"},

    // Species from discussion
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Predominant dairy starter culture bacteria found in Panchagavya metagenome", "taxon_name": "Lactococcus termiticola", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Predominant dairy starter culture species found in Panchagavya; widely used for cheese production"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Predominant dairy starter culture bacteria found in Panchagavya metagenome", "taxon_name": "Lactococcus fujiensis JCM 16395", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Predominant dairy starter culture species found in Panchagavya"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Predominant dairy starter culture bacteria found in Panchagavya metagenome", "taxon_name": "Lactococcus fujiensis", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Predominant dairy starter culture species found in Panchagavya"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Probiotic species discussed in context of Panchagavya therapeutic potential", "taxon_name": "Bacillus cereus", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Discussed as probiotic dietary supplement with immune stimulation and antimicrobial activities"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Probiotic species discussed in context of Panchagavya therapeutic potential", "taxon_name": "Bacillus subtilis", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Discussed as probiotic dietary supplement with immune stimulation and antimicrobial activities"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Probiotic species discussed in context of Panchagavya therapeutic potential", "taxon_name": "Lactobacillus camellia", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Discussed as probiotic dietary supplement"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Probiotic species discussed in context of Panchagavya therapeutic potential", "taxon_name": "Lactobacillus ozone", "reported_rank": "species", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Discussed as probiotic dietary supplement"},
    {"sample_code": "PG-3H", "food_name": "Panchagavya (3-hour old)", "description": "Probiotic species discussed in context of Panchagavya therapeutic potential", "taxon_name": "Paenibacillus", "reported_rank": "genus", "relative_abundance": null, "is_dominant": false, "measurement_type": "presence_only", "notes": "Discussed as probiotic dietary supplement with immune stimulation and antimicrobial activities"}
  ]
};
